# pragma once

#include "order_book.h"
#include "trade.h"


class MatchingEngine {
  public:
    explicit MatchingEngine(OrderBook& book);

    // Submit an order - engine matches what it can, rest all unfilled qty in the book
    // Returns all trades generated by this submission
    std::vector<Trade> submit(OrderPtr incoming);

  private:
    OrderBook& book_;

    // Stop orders waiting for their trigger price to be hit
    std::map<Price, std::deque<OrderPtr>> buy_stops_;  // ascending - trigger when price rises
    std::map<Price, std::deque<OrderPtr>, std::greater<Price>> sell_stops_;  // descending - trigger when price falls

    // Core matching loop
    std::vector<Trade> match(OrderPtr incoming);

    // After each fill, chick if any stop orders should now trigger
    std::vector<Trade> check_stops(Price last_price);
};