#pragma once

#include "order_book.h"
#include "trade.h"

#include <vector>
#include <unordered_map>


class MatchingEngine {
 public:
    explicit MatchingEngine(OrderBook& book);

    // Submit an order: match what you can, rest any unfilled qty in the book
    // Returns all trades generated by this submission
    std::vector<Trade> submit(OrderPtr incoming);

    const std::unordered_map<OrderID, int>& get_remaining() const { return remaining_qty_; }

 private:
    OrderBook& book_;

    // Tracks how much quantity remains for each resting order
    // Separate from Order::quantity_ which is the original immutable amount
    std::unordered_map<OrderID, int> remaining_qty_;

    // Stop orders waiting for their trigger price to be hit
    std::vector<OrderPtr> pending_stops_;

    // Core matching loop. Modifies 'remaining' in place
    std::vector<Trade> match(OrderPtr incoming, int& remaining);

    // After each fill, check if any stop orders should now trigger
    std::vector<Trade> check_stops(double last_price);
};